# Generated by Django 3.2 on 2022-07-20 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentalCenterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_date', models.DateField()),
                ('course_period', models.CharField(max_length=10)),
                ('course_week_order', models.IntegerField()),
                ('lab', models.CharField(max_length=100)),
                ('experimental_name', models.CharField(max_length=100)),
                ('experimental_item', models.CharField(max_length=100)),
                ('experimental_code', models.CharField(max_length=60)),
                ('teacher', models.CharField(max_length=50)),
                ('student_subject', models.CharField(max_length=50)),
                ('student_count', models.IntegerField()),
                ('experimental_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='MAIN.experimentalcentermodel')),
            ],
        ),
    ]
