# Generated by Django 3.2 on 2022-07-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursemodel',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='lab',
            field=models.CharField(default='无实验室房间信息', max_length=100),
        ),
    ]
