# Generated by Django 3.2 on 2022-07-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0002_auto_20220725_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='lab',
            field=models.CharField(default='无实验室房间信息', max_length=100, null=True),
        ),
    ]
